[package]
name = "DmByBot"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.0"
device_query = "2.1.0"
fantoccini = "0.21.2"
tokio = { version = "1.1.0", features = ["full"] }
enigo = "0.2.1"
display-info = "0.5.1"
serde_json = "1.0.137"
