[package]
name = "DmByBot"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev = "0.5.3"
winit = "0.30.5"
fantoccini = "0.21.2"
tokio = { version = "1.1.0", features = ["full"] }
execute = "0.2.13"
display-info = "0.5.1"